#!/usr/bin/env node

'use strict';

//console.log("Hello World");

//process.stdout.write("Hello World\n");

var out = process.stdout;


var c = require('skilstak-colors'); 



out.write(c. clear + c.rc() + "Hello World\n" + c.x);
