#!/usr/bin/env python3

import skilstak.colors as c

def hello():
    """Print 'Hello World!'"""
    print(c.o + "Hello!")

def take(name):
    """Takes your name and puts it in a sentence"""
    print(c.b + "This is your name in a sentence")
    print(c.g + "Have a good day " + name)
    
if __name__ == '__main__':
    hello()
    print(c.o + "What is your name?")
    name = input(c.y + "--->")
    take(name)
