#!/usr/bin/env python3

import hello as h

if __name__ == "__main__":
    from sys import argv


    option = ""
    name = " world"
    try:

        if len(argv) == 2:
            if argv[1].startswith("-"):
                option = argv[1]
            else:
                name = argv[1]
        if len(argv) > 2:
            option = argv[1]
            name = argv[2]
           
        message = "Hello " + name + "!"

        if option == "-m": 
            h.print_multi(message)

        elif option == "-p":
            h.print_pink(message)

        elif option == "-r":
            h.print_red(message)

        elif option == "-o": 
            h.print_orange(message)

        elif option == "-y":
            h.print_yellow(message)
    except KeyboardInterrupt:
        exit()
