#!/usr/bin/env python3

import skilstak.colors as c
import time

def print_plain(hello):
    print("hello")

def print_color(hello):
    while True:
         print(c.rc() +  hello, end=" ")

def print_multi(hello):
    while True:
         print(c.clear + c.multi(hello))
         time.sleep(0.5)


if __name__ == "__main__":
    from sys import argv

    name = " world"
    try:

        if len(argv) == 2:
            name = argv[1]

        print_color("hello" + name + "!")

    except KeyboardInterrupt:
        exit()
